### ISSUE TITLE
bug: adding chain on mobile Metamask app that doesn't exist yields exception of type UserRejectedRequestError 

### ISSUE THREAD

**Issue by 0xMaestr0** [wagmi-dev/viem#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.7

### Current Behavior

When attempting to switch to a mobile app Metamask chain that's not yet added, an exception of type UserRejectedRequestError will be thrown

### Expected Behavior

The thrown exception should be of type SwitchChainError

### Steps To Reproduce

Connect Metamask wallet from an Android Chrome browser and request switching to a chain that doesn't already exist. In my case, I used Walletconnect's web3modal.

**Comment by jxom** [comment]
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

My guess from reading this is that it is probably a MetaMask issue. We just forward on the error returned from the Provider. In this case, MetaMask might be giving us a `4001` error code instead of a `4902`.

Please reopen this issue when a reproduction is added.
