### ISSUE TITLE
bug: decodeEventLog topics type error when cycling getLogs data

### ISSUE THREAD

**Issue by ryeshrimp** [wagmi-dev/viem#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.1.7

### Current Behavior

> Type 'TopicFilter' is not assignable to type '[signature: `0x${string}`, ...args: LogTopic[]]'.
  Source provides no match for required element at position 0 in target.ts(2322)

### Expected Behavior

No type error

### Steps To Reproduce

```
const logs = await client.getLogs();

logs.forEach((log) => {
  const eventData = decodeEventLog({
    abi: [],
    data: log.data,
    topics: log.topics,
  });
});
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-vqwqeb?file=index.ts

**Comment by 0xOlias** [comment]
Related [discussion](https://github.com/wagmi-dev/viem/discussions/163) and [PR](https://github.com/wagmi-dev/viem/pull/178).

It may not make sense for `decodeEventLog` to require the first element of the `topics` array to be a `Hex`, because anonymous events with no indexed parameters have `topics == []`.

Related question: does `decodeEventLog` work for anonymous events at the moment?

**Comment by jxom** [comment]
Not right now. I'm not sure you can decode `data` from an anonymous log if you can't derive the event signature.

**Comment by 0xOlias** [comment]
I suspect the original issue here (the type error) remains, because [`decodeEventLog`](https://github.com/wagmi-dev/viem/blob/main/src/utils/abi/decodeEventLog.ts#L25
) expects `topics: [signature: Hex, ...args: TTopics[]]` while the return type of `Log` has `topics: Hex[]` which is not assignable to `[signature: Hex, ...args: TTopics[]]`.

Basically, the problem is `decodeEventLog` requires the first topic to be present, but logs returned by the RPC are not guaranteed to have the first topic present.

Perhaps `decodeEventLog` should throw a runtime error if `topics[0]` is undefined. Then, the argument could be typed as `topics: [signature: Hex | undefined, ...args: TTopics]` and rely on the runtime check to make sure `signature: Hex`. The rest of the function body would remain unchanged.

**Comment by jxom** [comment]
Good catch! PR at #205.
