### ISSUE TITLE
bug: decodeFunctionResult return not is object data

### ISSUE THREAD

**Issue by smurfiofficial** [wagmi-dev/viem#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.14

### Current Behavior

When i call 
```
import { decodeFunctionResult } from 'viem'
const wagmiAbi = [{
        inputs: [],
        name: "latestRoundData",
        outputs: [
            { internalType: "uint80", name: "roundId", type: "uint80" },
            { internalType: "int256", name: "answer", type: "int256" },
            { internalType: "uint256", name: "startedAt", type: "uint256" },
            { internalType: "uint256", name: "updatedAt", type: "uint256" },
            { internalType: "uint80", name: "answeredInRound", type: "uint80" },
        ],
        stateMutability: "view",
        type: "function",
    }]
const value = decodeFunctionResult({
  abi: wagmiAbi,
  functionName: 'latestRoundData',
  data: '0x00000000000000000000000000000000000000000000000100000000000027ba000000000000000000000000000000000000000000000000000002940e47c580000000000000000000000000000000000000000000000000000000006433e11f000000000000000000000000000000000000000000000000000000006433e11f00000000000000000000000000000000000000000000000100000000000027ba'
})

console.log(value);
```

It return
`[
  18446744073709561786n,
  2834918000000n,
  1681121567n,
  1681121567n,
  18446744073709561786n
]`

### Expected Behavior

It will return object 
`{roundId: 18446744073709561786n,
  answer: 2834918000000n
  startedAt: 1681121567n,
  updatedAt: 1681121567n,
  answeredInRound: 18446744073709561786n
  }`

**Comment by smurfiofficial** [comment]
I found viem not using standard solidity abi, so how to convert standard abi to viem abi?

**Comment by jxom** [comment]
This is expected. The input (`abiItem.outputs`) is an array of types, so you get an array of decoded values as the return type. viem only maps explicitly typed tuples as objects. 

If you’d prefer an object as the return type, you could convert the parameters to a tuple and it should still work.

```
outputs: {
  components: [
    { internalType: "uint80", name: "roundId", type: "uint80" },
    { internalType: "int256", name: "answer", type: "int256" },
    { internalType: "uint256", name: "startedAt", type: "uint256" },
    { internalType: "uint256", name: "updatedAt", type: "uint256" },
    { internalType: "uint80", name: "answeredInRound", type: "uint80" },
  ],
  type: “tuple”
}  
 ```

**Comment by jxom** [comment]
viem does use standard solidity ABI.

**Comment by smurfiofficial** [comment]
> 

So how to convert from standard solidity ABI to this.
I follow this function from https://goerli.arbiscan.io/address/0x6550bc2301936011c1334555e62A87705A81C12C#readContract
It returns object data

**Comment by jxom** [comment]
Etherscan just adds friendly labels to the decoded data.

Here is the definition you are talking about:

```
function latestRoundData() external view
  returns (
    uint80 roundId,
    int256 answer,
    uint256 startedAt,
    uint256 updatedAt,
    uint80 answeredInRound
  );
```

This function returns a set of 5 items, so viem maps it to an array. The reason why we don't convert it to an object is because things get ambiguous when we come to decode structs. How do you determine the difference between a "return" tuple (above) and a "struct" tuple (seen below):

```
struct Data {
  uint80 roundId;
  uint256 answer;
  uint256 startedAt;
  uint256 updatedAt;
  uint80 answeredInRound
}

function latestRoundData() external view returns (Data data);
``` 

Another reason is that folks might expect it to be an array (because it is a set of return items). I understand Ethers mitigates this by returning a hybrid Array/Object type, but that kind of type is not serializable in JavaScript, and viem prefers to not try and "hack" JavaScript types.

**Comment by MidnightLightning** [comment]
> How do you determine the difference between a "return" tuple (above) and a "struct" tuple?

I believe the key difference is whether the outputs are named or not:

```
function latestRoundData() external view
  returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);
```

```
function latestRoundData() external view
  returns (uint80, int256, uint256, uint256, uint80);
```

The former gives additional data (aliases) in the human-friendly structure that  would be useful to the human developer on the output. A project defining their ABIs that way then allows developers to do

```
const data = await readContract({ ... })
console.log(data.startedAt)
```

without needing to know `startedAt` is index 2 of that result object, which is very helpful for efficient coding. As a drop-in replacement for EthersJS, this is a different behavior when parsing a human-friendly ABI structure (EthersJS outputs a custom object that has both numeric and named keys, so `data.startedAt` and `data[2]` both work).

You gave a workaround solution @jxom for those structuring their ABI directly, but for parsing human-friendly ABIs using `parseABI`, it would be good to either have an input parameter to choose to have a named (tuple) output, or to use the logic of "if all the output parameters are named, assume they want an object output with named keys, rather than an array output".

**Comment by MidnightLightning** [comment]
Found a potential workaround for my situation: Going from:

```
parseAbi([
  'function latestRoundData() external view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)'
])
```

to:

```
parseAbi([
  'function latestRoundData() external view returns ((uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound))'
])
```

(adding another set of parenthesis around the output values) causes viem to have the desired effect, even if the smart contract wasn't compiled with that output structure wrapped in a tuple like that.

**Comment by jxom** [comment]
Keep in mind, the above solution only works if the children type sizes are static (uint, bool, bytes32, etc) and not dynamic (string, bytes, etc).
