### ISSUE TITLE
Can't use getBalance with Velas RPC

### ISSUE THREAD

**Issue by 0xsambugs** [wagmi-dev/viem#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.0

### Current Behavior

When I'm trying to use a Velas RPC to get the balance of an account, it throws the following error:
```Cannot convert undefined to a BigInt```

For what I could see, the RPC call returns `undefined`. Then, the client tries to convert to BigInt, which causes the error. The weird thing is that Ethers works fine with the same RPC:
```
/// This doesn't fail, and returns a valid amount
const balance = await new JsonRpcProvider('https://evmexplorer.velas.com/rpc')
      .getBalance('0x000000000000000000000000000000000000dead')
```

### Expected Behavior

`getBalance` should not revert and it would return the actual balance

### Steps To Reproduce

```
const balance = await createPublicClient({ transport: http('https://evmexplorer.velas.com/rpc') })
      .getBalance({ address: '0x000000000000000000000000000000000000dead' })
```

**Comment by 0xsambugs** [comment]
Please let me know if I'm doing something wrong and I'll try to get it fixed. And thank you for your time 🙏

**Comment by fubhy** [comment]
That's because `velas` eth rpc api does not support block numbers as hex. 

Their documentation states that their eth rpc api is compatible with the ethereum json rpc spec but it appears that that's false: https://evmexplorer.velas.com/eth-rpc-api-docs

If you know anyone there, I'd suggest to reach out to them and inform them about this. If they intend to be compatible with ethereum json rpc, then this is a bug on their side.

In the meantime, you can get around this by explicitly using block tags:

```typescript
const client = createPublicClient({
  transport: http('https://evmexplorer.velas.com/api/eth-rpc'),
})

const balance = await client.getBalance({
  address: '0x000000000000000000000000000000000000dead',
  blockTag: 'latest',
})
```

**Comment by 0xsambugs** [comment]
Thank you so much for the quick response and the help debugging @fubhy 🙏 

I'll try to raise this with the Velas team!
