### ISSUE TITLE
bug: viem's hashMessage doesn't match ethers' hashMessage in certain cases

### ISSUE THREAD

**Issue by VladimirMikulic** [wagmi-dev/viem#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.20

### Current Behavior

```js
viem.hashMessage("test") === ethers.hashMessage("test") // true
viem.hashMessage("0x617070726f76652072756770756c6c0000000000000000000000000000000000") === ethers.hashMessage("0x617070726f76652072756770756c6c0000000000000000000000000000000000") // false!
```

### Expected Behavior

I'd expect Viem's hashMessage to match ethers' hashMessage or at least that differences/edge cases are documented.

### Steps To Reproduce

Please check sandbox.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/infallible-ben-zkj7f5

**Comment by jxom** [comment]
Are you trying to hash hex as bytes or hex as string? 

viem only supports hashing "string" messages, but not messages represented as bytes (via hex or uint8array). 

It's _kinda_ documented as [`message` is a `string`](https://viem.sh/docs/utilities/hashMessage.html#parameters) instead of `Hex`, but can add a note to make it clearer.

**Comment by VladimirMikulic** [comment]
I really appreciate your fast response here @jxom!
Glad that I stumbled on this early so it gets addressed.
Btw, great work on the library overall!
