### ISSUE TITLE
Types error in usePrepareContractWrite 

### ISSUE THREAD

**Issue by osla-dev** [wagmi-dev/viem#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.24

### Current Behavior

![viem error](https://github.com/wagmi-dev/viem/assets/71358698/80988f60-2989-4f8d-bcd5-461e56fd5a75)

### Expected Behavior

Type value should be "bigint" or "undefined"

**Comment by jxom** [comment]
I can't seem to reproduce this in a minimal TS environment: https://www.typescriptlang.org/play?target=8#code/JYWwDg9gTgLgBAbzgVwM4FMAKV1gIY4DCEAdjFHgMYwDqUwM6ANHOlJQOwBMAjAIIAhAJJwAvnABmUCCDgByAO54A5iGByAUBrRYc+IqXJVa9RgAoEGuNbh4ARsABcrdt37CmVm3gAmPnKioznIADAAecp42ksgk1MCkAHJ4IOjBeGBg0gBu6JFe1gTKQXAA2qERLDwkALpRNtl4ADbIaXDVGqIAlEA

Also, `usePrepareContractWrite` exists in wagmi, not viem. Do you think you could provide a minimal reproducible example via a separate repository or https://new.wagmi.sh? Going to close this issue here, but can you re-open it on the wagmi repo **with a minimal reproducible example**?
