### ISSUE TITLE
bug: Error: Cannot convert a BigInt value to a number at toHex.js

### ISSUE THREAD

**Issue by uselesss** [wagmi-dev/viem#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.33

### Current Behavior

Getting a "Cannot convert a BigInt value to a number" error while connecting to WalletConnect v2 provider at runtime due to invalid es compilation

Package-json browserslist config: 
"browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all"
]

### Anything else?

Can be fixed by changing line 174 at toHex.js from
`else maxValue = 2n ** (BigInt(size) * 8n) - 1n`
to
`else maxValue = BigInt(2 ** (size * 8) - 1);`

**Comment by jxom** [comment]
This seems to happen due to the way the [bundler treats bigint values according to the browserslist](https://github.com/babel/babel/issues/13109). While the proposed solution does fix it for that exact case, there could be other cases where we may perform operations on those values (ie. `maxValue ** BigInt(2)`) which would break.

The recommended solution would be to modify the browserslist to filter out very old browsers like IE and ancient Android browsers: https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299
