### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by webnatrix** [wagmi-dev/viem#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1

### Anything else?

MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"dynamicfee tx is not supported by signer Signer[chainId=97,malleable=false,unprotected=true,protected=true,accesslist=false,dynamicfee=false"}}}' {code: -32603, message: `[ethjs-query] while formatting outputs from RPC '{…ected=true,accesslist=false,dynamicfee=false"}}}'`}

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.
