### ISSUE TITLE
bug: getEnsName throws an error

### ISSUE THREAD

**Issue by ilamanov** [wagmi-dev/viem#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.13

### Current Behavior

There was an attempt to fix this issue already (#595) but looks like it hasn't been fully solved

Trying to call `publicClient.getEnsName` with address `0x00000000000061aD8EE190710508A818aE5325C3` (on Ethereum mainnet) throws the following error:

```
Error: The contract function "reverse" reverted with the following reason:
UniversalResolver: Wildcard on non-extended resolvers is not supported

Contract Call:
  address:   0xc0497E381f536Be9ce14B0dD3817cBcAe57d2F62
  function:  reverse(bytes reverseName)
  args:             (0x28303030303030303030303030363161643865653139303731303530386138313861653533323563330461646472077265766572736500)

Docs: https://viem.sh/docs/contract/readContract.html
Version: viem@1.2.12
```

The same behavior is observed with this address: `0x0904Dac3347eA47d208F3Fd67402D039a3b99859` (also on Ethereum mainnet)

### Expected Behavior

ethers.js on the other hand returns "ret↩️rn.eth" for `0x00000000000061aD8EE190710508A818aE5325C3`

### Steps To Reproduce

Run the below StackBlitz and take a look at the error in Chrome Developer Console

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/wagmi-dev-viem-smqty8?file=index.ts

**Comment by jxom** [comment]
@TateB any ideas?

**Comment by TateB** [comment]
there is a bug here in that `getEnsName()` is erroring, this should be handled like it is in `getEnsAddress()` and return `null`.

the reason ethers returns the name is because ethers is doing normalisation on the reverse record's `name` value, and your `name` value isn't normalised (see [here](https://adraffy.github.io/ens-normalize.js/test/resolver.html#ret%E2%86%A9%EF%B8%8Frn.eth)). it probably shouldn't do that, but there has never been an exact spec for it. i think it makes sense for ethers to change their implementation.

**Comment by ilamanov** [comment]
Great, thank you for the quick fix!
